// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-tnJ4jAU3nh4GekEIR0toUmGLAa4UeW4',
    appId: '1:1044002664740:web:35d2e7210cbdda1465c3b1',
    messagingSenderId: '1044002664740',
    projectId: 'todo-2dd1b',
    authDomain: 'todo-2dd1b.firebaseapp.com',
    storageBucket: 'todo-2dd1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBPeWXIjQf0FX7skQGcfhUFc19VtRjsSk',
    appId: '1:1044002664740:android:5865f431bc67211c65c3b1',
    messagingSenderId: '1044002664740',
    projectId: 'todo-2dd1b',
    storageBucket: 'todo-2dd1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARUgYfVuKBpalP-SyzRnrY3IIq0uALzXE',
    appId: '1:1044002664740:ios:35692a6b78c8d22765c3b1',
    messagingSenderId: '1044002664740',
    projectId: 'todo-2dd1b',
    storageBucket: 'todo-2dd1b.appspot.com',
    iosBundleId: 'com.example.todoApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARUgYfVuKBpalP-SyzRnrY3IIq0uALzXE',
    appId: '1:1044002664740:ios:b06dbc727706f79965c3b1',
    messagingSenderId: '1044002664740',
    projectId: 'todo-2dd1b',
    storageBucket: 'todo-2dd1b.appspot.com',
    iosBundleId: 'com.example.todoApp2.RunnerTests',
  );
}
